export const AdminMenu = [
  {
    name: 'dashboard',
    icon: 'dashboard',
    url: 'dashboard',
    id: 'dashboard_01',
  },
  {
    name: 'Live Orders',
    icon: 'fiShoppingCart',
    url: 'orders-board',
    id: 'orders-board'
  },
  {
    name: 'pos.system',
    icon: 'laptop',
    url: 'pos-system',
    id: 'pos.system_01',
  },
  {
    name: 'order',
    id: 'order.management',
    icon: 'fiShoppingCart',
    submenu: [
      {
        name: 'Eagle View',
        icon: 'TbSitemap',
        id: 'deliveries_map',
        url: 'deliveries/map',
        children: [],
      },
      {
        name: 'delivery.orders',
        icon: 'TbTruckDelivery',
        url: 'orders-board/delivery',
        id: 'order-list-delivery',
        children: [],
      },
      {
        name: 'pickup.orders',
        icon: 'lightning',
        url: 'orders-board/pickup',
        id: 'order-list-pickup',
        children: [],
      },
      {
        name: 'scheduled.orders',
        icon: 'clock',
        url: 'orders-board/scheduled',
        id: 'order-list-schedule',
        children: [],
      },
      {
        name: 'waiting.payment.orders',
        icon: 'wallet',
        url: 'orders-list/waiting-payment',
        id: 'order-list-waiting-payment',
        children: [],
      },
      {
        name: 'refunds',
        icon: 'TbReceiptRefund',
        url: 'refunds',
        id: 'refunds_02',
        children: [],
      },
      {
        name: 'order.status',
        icon: 'RiFileSettingsLine',
        url: 'settings/orderStatus',
        id: 'order.status',
        children: [],
      },
    ],
  },
  {
    name: 'Stores',
    id: 'shop.management_04',
    icon: 'shop',
    submenu: [
      {
        name: 'Stores',
        icon: 'shop',
        url: 'shops',
        id: 'shops',
        children: [],
      },
      {
        name: 'Store Tags',
        icon: 'shop',
        url: 'shop-tag',
        id: 'tag',
        children: [],
      },
      {
        name: 'categories',
        icon: 'appStore',
        url: 'catalog/shop/categories',
        id: 'shop.categories',
        children: [],
      },
    ],
  },
  {
    name: 'product',
    id: 'food.management',
    icon: 'branches',
    submenu: [
      {
        name: 'products',
        icon: 'dropbox',
        url: 'catalog/products',
        id: 'food',
        children: [],
      },
      {
        name: 'units',
        icon: 'disconnect',
        url: 'catalog/units',
        id: 'units',
        children: [],
      },
      {
        name: 'recepts',
        icon: 'recept',
        url: 'catalog/recept',
        id: 'recept',
        children: [],
      },
      {
        name: 'addons',
        icon: 'SlPuzzle',
        url: 'catalog/addons',
        id: 'addons',
        children: [],
      },
      {
        name: 'extras',
        icon: 'branches',
        url: 'catalog/extras/list',
        id: 'extras',
        children: [
          {
            name: 'extra.group',
            icon: 'groupOutlined',
            url: 'catalog/extras',
            id: 'extra.group',
          },
          {
            name: 'extra.value',
            icon: 'unGroupOutlined',
            url: 'catalog/extras/value',
            id: 'extra.value',
          },
        ],
      },
      {
        name: 'categories',
        icon: 'appStore',
        url: 'catalog/categories',
        id: 'categories',
        children: [],
      },

      // {
      //   name: 'recipe.categories',
      //   icon: 'appStore',
      //   url: 'catalog/recipe-categories',
      //   id: 'recipe.categories',
      //   children: [],
      // },
      // {
      //   name: 'menu.categories',
      //   icon: 'appStore',
      //   url: 'catalog/menu/categories',
      //   id: 'menu.categories',
      //   children: [],
      // },
    ],
  },
  {
    name: 'users',
    id: 'user_list',
    icon: 'user',
    submenu: [
      {
        name: 'Customers',
        icon: 'user',
        url: 'users/user',
        id: 'user',
      },
      {
        name: 'users',
        icon: 'userGroupAdd',
        url: 'users/admin',
        id: 'userGroupAdd',
      },
      {
        name: 'roles',
        icon: 'userSwitch',
        url: 'users/role',
        id: 'userSwitch',
      },
    ],
  },
  {
    name: 'deliveryman',
    id: 'deliveryman.management',
    icon: 'CarOutlined',
    submenu: [
      {
        name: 'Delivery Man',
        icon: 'TbTruckDelivery',
        id: 'deliveries_list',
        url: 'deliveries/list',
        children: [],
      },
      {
        name: 'deliveryman.request',
        icon: 'QuestionCircleOutlined',
        url: 'deliveryman/request',
        id: 'deliveryman-request_01',
        children: [],
      },
    ],
  },
  {
    name: 'marketing',
    id: 'restaurant.management_05',
    icon: 'copyright',
    submenu: [
      {
        name: 'cashback',
        icon: 'copyright',
        url: 'cashback',
        id: 'cashback_01',
        children: [],
      },
      {
        name: 'coupons',
        icon: 'calendar',
        url: 'coupons',
        id: 'coupons',
        children: [],
      },
      {
        name: 'referral',
        icon: 'referral',
        url: 'settings/referal',
        id: 'referral_02',
        children: [],
      },
      {
        name: 'bonus',
        icon: 'GiftOutlined',
        url: 'bonus/list',
        id: 'bonus_02',
        children: [],
      },
      {
        name: 'notifications',
        icon: 'notificationsActive',
        url: 'notifications',
        id: 'notifications',
        children: [],
      },
      {
        name: 'email.subscriber',
        icon: 'mail',
        url: 'email/subscriber',
        id: 'email.subscriber_01',
        children: [
          {
            name: 'subscriber',
            icon: 'MdNotificationAdd',
            url: 'subscriber',
            id: 'subscriber',
          },
          {
            name: 'message.subscriber',
            icon: 'MdNotificationAdd',
            url: 'message/subscriber',
            id: 'message.subscriber',
          },
        ],
      },
    ],
  },

  {
    name: 'transaction',
    id: 'transaction.management',
    icon: 'transaction',
    submenu: [
      {
        name: 'transactions',
        icon: 'transaction',
        url: 'transactions',
        id: 'transactions',
        children: [],
      },
      {
        name: 'payout.requests',
        icon: 'dollar',
        url: 'payout-requests',
        id: 'payout-requests',
        children: [],
      },
      {
        name: 'payouts',
        icon: 'moneyOut',
        url: 'payouts',
        id: 'admin.payouts',
        children: [],
      },
      // {
      //   name: 'subscriptions',
      //   icon: 'imSubscript',
      //   url: 'subscriptions',
      //   id: 13,
      //   children: [],
      // },
      {
        name: 'wallets',
        icon: 'wallet',
        url: 'wallets',
        id: 'wallets_01',
        children: [],
      },
      {
        name: 'payment.to.sellers',
        icon: 'moneyOut',
        id: 'withdraws',
        children: [
          {
            name: 'payment.to.sellers',
            icon: 'moneyOut',
            url: 'withdraws/seller',
            id: 'withdraws.seller_uncomplete',
          },
          {
            name: 'completed.payments',
            icon: 'check',
            url: 'completed-withdraws/seller',
            id: 'withdraws.completed_seller_uncomplete',
          },
        ],
      },
      {
        name: 'payment.to.deliverymans',
        icon: 'TbTruckDelivery',
        id: 'withdraw.deliverymans',
        // url: 'payments/deliverymans',
        children: [
          {
            name: 'payment.to.deliverymans',
            icon: 'TbTruckDelivery',
            url: 'withdraws/deliveryman',
            id: 'withdraw.deliverymans_uncomplete',
          },
          {
            name: 'completed.payments',
            icon: 'check',
            url: 'completed-withdraws/deliveryman',
            id: 'withdraw.completed_deliverymans_uncomplete',
          },
        ],
      },
    ],
  },
  {
    name: 'analytics.and.reports',
    id: 'analytics',
    icon: 'products',
    submenu: [
      {
        name: 'products',
        icon: 'products',
        url: 'report/products',
        id: 'report-products',
        children: [],
      },
      {
        name: 'order',
        icon: 'orders',
        url: 'report/orders',
        id: 'report-orders',
        children: [],
      },
      {
        name: 'stock',
        icon: 'stock',
        url: 'report/stock',
        id: 'report-stock',
        children: [],
      },
      {
        name: 'delivery.statistics',
        icon: 'ImStatsDots',
        id: 'delivery.statistics',
        url: 'delivery/statistics',
        children: [],
      },
      {
        name: 'category',
        icon: 'categories',
        url: 'report/categories',
        id: 'report-categories',
        children: [],
      },
      {
        name: 'overview',
        icon: 'overview',
        url: 'report/overview',
        id: 'report-overview',
        children: [],
      },
      {
        name: 'revenue',
        icon: 'revenue',
        url: 'report/revenue',
        id: 'report-revenue',
        children: [],
      },
      {
        name: 'variation',
        icon: 'variation',
        url: 'report/extras',
        id: 'report-variation',
        children: [],
      },
    ],
  },

  {
    name: 'content',
    id: 'content.management',
    icon: 'appStoreAdd',
    submenu: [
      // {
      //   name: 'brands',
      //   icon: 'appStoreAdd',
      //   url: 'catalog/brands',
      //   id: 'brands',
      //   children: [],
      // },
      {
        name: 'page.setup',
        icon: 'settings',
        url: 'settings',
        id: 'page.setup',
        children: [
          {
            name: 'faq',
            icon: 'questionCircle',
            url: 'settings/faqs',
            id: 'faq',
          },
          {
            name: 'terms',
            icon: 'paperClip',
            url: 'settings/terms',
            id: 'terms',
          },
          {
            name: 'policy',
            icon: 'lock',
            url: 'settings/policy',
            id: 'policy',
          },
          {
            name: 'pages',
            icon: 'RiPageSeparator',
            url: 'pages',
            id: 'pages',
          },
          {
            name: 'landing.page',
            icon: 'FileTextOutlined',
            url: 'settings/landing-page',
            id: 'settings/landing-page',
          },
        ],
      },
      // {
      //   name: 'career',
      //   icon: 'CaretUpOutlined',
      //   url: 'careers/list',
      //   id: 'career.list',
      //   children: [
      //     {
      //       name: 'career',
      //       icon: 'caretUp',
      //       url: 'catalog/career',
      //       id: 'catalog.career',
      //       children: [],
      //     },
      //     {
      //       name: 'career.categories',
      //       icon: 'careerCategory',
      //       url: 'catalog/career-categories',
      //       id: 'career.categories',
      //       children: [],
      //     },
      //   ],
      // },
      {
        name: 'banners',
        icon: 'bsImage',
        url: 'banners',
        id: 'banners',
        children: [],
      },
      {
        name: 'blogs',
        url: 'blogs',
        icon: 'form',
        id: 'blogs_02',
        children: [],
      },
      // {
      //   name: 'stories',
      //   icon: 'BsClockHistory',
      //   url: 'stories',
      //   id: 'stories',
      //   children: [],
      // },
      {
        name: 'gallery',
        url: 'gallery',
        icon: 'fiImage',
        id: 'gallery',
        children: [],
      },
    ],
  },

  {
    name: 'Reviews',
    id: 'reviews',
    icon: 'star',
    submenu: [
      {
        name: 'Store Reviews',
        icon: 'fiShoppingCart',
        url: 'shop-reviews',
        id: 'shop-review_01',
        children: [],
      },
      {
        name: 'Order Reviews',
        icon: 'star',
        url: 'reviews/order',
        id: 'order-review_01',
        children: [],
      },
      {
        name: 'product.reviews',
        icon: 'skin',
        url: 'reviews/product',
        id: 'product-review',
        children: [],
      },
      {
        name: 'deliveryboy.reviews',
        icon: 'TbTruckDelivery',
        url: 'reviews/deliveryboy',
        id: 'deliveryboy-reviews_01',
        children: [],
      },
    ],
  },

  { name: 'ads',
    id: 'advert.management',
    icon: 'appStoreAdd',
    submenu: [
      {
        name: 'ads',
        id: 'ads',
        url: 'catalog/advert',
        icon: 'appStore',
      },
      {
        name: 'shop.ads',
        id: 'shop_ads',
        url: 'catalog/shop-ads',
        icon: 'appStore',
      },
    ],
  },


  {
    name: 'Settings',
    id: 'business.settings_02',
    icon: 'settings',
    url: 'settings/general',
  },
  // { name: 'business.settings',
  //   id: 'business.settings_02',
  //   icon: 'settings',
  //   submenu: [
  //     {
  //       name: 'settings.general',
  //       icon: 'settings',
  //       url: 'settings/general',
  //       id: 'settings.general_02',
  //       children: [],
  //     },
  //     {
  //       name: 'currencies',
  //       icon: 'moneyCollect',
  //       url: 'currencies',
  //       id: 'currencies',
  //       children: [],
  //     },
  //     {
  //       name: 'payments',
  //       icon: 'wallet',
  //       url: 'settings/payments',
  //       id: 'payments',
  //       children: [],
  //     },
  //     {
  //       name: 'payment.payloads',
  //       icon: 'payload',
  //       url: 'payment-payloads',
  //       id: 'payment.payloads',
  //       children: [],
  //     },
  //     {
  //       name: 'sms-payload',
  //       icon: 'message',
  //       url: 'settings/sms-payload',
  //       id: 'sms-payload',
  //       children: [],
  //     },
  //     {
  //       name: 'email.provider',
  //       icon: 'emailSettings',
  //       url: 'settings/emailProviders',
  //       id: 'settings_email.provider_02',
  //       children: [],
  //     },
  //     {
  //       name: 'notification.settings',
  //       icon: 'notificationsActive',
  //       url: 'settings/firebase',
  //       id: 'notification.settings',
  //       children: [],
  //     },
  //     {
  //       name: 'social.settings',
  //       icon: 'instagram',
  //       url: 'settings/social',
  //       id: 'instagram_social-settings_01',
  //       children: [],
  //     },
  //     {
  //       name: 'app.settings',
  //       icon: 'GrAppleAppStore',
  //       url: 'settings/app',
  //       id: 'app-settings',
  //       children: [],
  //     },
  //   ],
  // },
  // { name: 'system.settings',
  //   id: 'system.settings_01',
  //   icon: 'global',
  //   submenu: [
  //     {
  //       name: 'languages',
  //       icon: 'global',
  //       url: 'settings/languages',
  //       id: 'languages_02',
  //       children: [],
  //     },
  //     {
  //       name: 'translations',
  //       icon: 'translation',
  //       url: 'settings/translations',
  //       id: 'translations_01',
  //       children: [],
  //     },
  //     // {
  //     //   icon: 'database',
  //     //   url: 'settings/backup',
  //     //   name: 'backup',
  //     //   id: 'backup_01',
  //     //   children: [],
  //     // },
  //     // {
  //     //   name: 'system.information',
  //     //   icon: 'tool',
  //     //   url: 'settings/system-information',
  //     //   id: 'settings/system-informations_tool_01',
  //     //   children: [],
  //     // },
  //     // {
  //     //   name: 'update',
  //     //   icon: 'cloudUpload',
  //     //   url: 'settings/update',
  //     //   id: 'update',
  //     //   children: [],
  //     // },
  //     // {
  //     //   icon: 'cloudUpload',
  //     //   url: 'settings/bookingUpload',
  //     //   name: 'bookingUpload',
  //     //   id: 'bookingUpload',
  //     //   children: [],
  //     // },
  //     // {
  //     //   icon: 'AiOutlineClear',
  //     //   url: 'settings/cashClear',
  //     //   name: 'clear.cash',
  //     //   id: 'clear_cash_02',
  //     //   children: [],
  //     // },
  //   ],
  // },
  // {
  //   name: 'appstore',
  //   icon: 'logout',
  //   url: 'appstore',
  //   id: 'appstore',
  // },
  {
    name: 'logout',
    icon: 'logout',
    url: '',
    id: 'logout_04',
  },
];
