export const SellerMenu = [
  {
    name: 'dashboard',
    icon: 'dashboard',
    url: 'dashboard',
    id: 'dashboard_03',
    role: 'admin',
  },
  {
    name: 'pos.system',
    icon: 'laptop',
    url: 'seller/pos-system',
    id: 'pos-system',
  },
  {
    name: 'wallet',
    id: 'wallet',
    icon: 'wallet',
    url: 'seller/wallet',
  },
  // {
  //   name: 'reservation',
  //   id: 'order_management',
  //   icon: 'BookOutlined',
  //   submenu: [
  //     {
  //       name: 'reservation.list',
  //       icon: 'BsCalendarCheck',
  //       url: 'seller/bookingList',
  //       id: 'seller/BookingList',
  //       children: [],
  //     },
  //     {
  //       name: 'reservation',
  //       icon: 'BsCalendarCheck',
  //       url: 'seller/booking',
  //       id: 'seller/booking',
  //       children: [],
  //     },
  //     {
  //       name: 'reservation.zone',
  //       icon: 'BiMapPin',
  //       url: 'seller/booking/zone',
  //       id: 'seller-reservation-zone',
  //       children: [],
  //     },
  //     {
  //       name: 'tables.and.qrcode',
  //       icon: 'QrcodeOutlined',
  //       url: 'seller/booking/tables',
  //       id: 'reservation-tables',
  //       children: [],
  //     },
  //     {
  //       name: 'reservation.time',
  //       icon: 'AiOutlineFieldTime',
  //       url: 'seller/booking/time',
  //       id: 'reservation-time',
  //       children: [],
  //     },
  //   ],
  // },
  {
    name: 'order',
    id: 'order_management',
    icon: 'fiShoppingCart',
    submenu: [
      {
        name: 'all.orders',
        icon: 'fiShoppingCart',
        url: 'seller/orders-board',
        id: 'orders-board',
        children: [],
      },
      // {
      //   name: 'dine.in.orders',
      //   icon: 'MdOutlineTableBar',
      //   url: 'seller/orders-board/dine_in',
      //   id: 'orders-board-dine-in',
      //   children: [],
      // },
      {
        name: 'waiting.payment.orders',
        icon: 'wallet',
        url: 'seller/orders-list/waiting-payment',
        id: 'order-list-waiting-payment',
        children: [],
      },
      {
        name: 'reviews',
        icon: 'star',
        url: 'seller/reviews/order',
        id: 'order-review_01',
        children: [],
      },
      // {
      //   name: 'refunds',
      //   icon: 'TbReceiptRefund',
      //   url: 'seller/refunds',
      //   id: 'refunds_01',
      //   children: [],
      // },
    ],
  },
  {
    name: 'Stores',
    id: 'restaurants_management',
    icon: 'shop',
    submenu: [
      {
        name: 'My Stores',
        icon: 'shop',
        url: 'my-shop',
        id: 'my-shop',
      },
      {
        name: 'Store Reviews',
        icon: 'star',
        url: 'seller/shop-reviews',
        id: 'shop-reviews',
      },
      {
        name: 'branch',
        icon: 'branchesOutlined',
        url: 'seller/branch',
        id: 'branch',
        children: [],
      },
      {
        name: 'users',
        icon: 'user',
        url: 'seller/shop-users',
        id: 'users',
        children: [],
      },
    ],
  },
  {
    name: 'product',
    id: 'food_management',
    icon: 'branches',
    submenu: [
      {
        icon: 'SlPuzzle',
        url: 'seller/addons',
        name: 'addons',
        id: 'addons',
        children: [],
      },
      {
        name: 'recepts',
        icon: 'recept',
        url: 'seller/recept',
        id: 'recept',
        children: [],
      },
      {
        name: 'discounts',
        icon: 'euroCircle',
        url: 'seller/discounts',
        id: 'discounts',
        children: [],
      },
      {
        icon: 'dropbox',
        url: 'seller/products',
        name: 'product',
        id: 'dropbox',
        children: [],
      },
      {
        name: 'product.categories',
        icon: 'appStore',
        url: 'seller/categories',
        id: 'categories',
        children: [],
      },
      {
        name: 'recipe.categories',
        icon: 'appStore',
        url: 'seller/recipe-categories',
        id: 'recipe.categories',
        children: [],
      },
      {
        icon: 'branches',
        url: 'extras',
        name: 'extra.group',
        id: 'branches',
        children: [],
      },
      {
        icon: 'branches',
        url: 'extras/value',
        name: 'extra.value',
        id: 'extra_value',
        children: [],
      },
      {
        name: 'product.reviews',
        icon: 'skin',
        url: 'seller/reviews/product',
        id: 'product-review',
        children: [],
      },
    ],
  },
  {
    name: 'marketing',
    id: 'restaurant_management_03',
    icon: 'calendar',
    submenu: [
      {
        name: 'coupons',
        icon: 'calendar',
        url: 'coupons',
        id: 'coupons',
        children: [],
      },
      {
        icon: 'GiftOutlined',
        name: 'shop.bonus',
        url: 'seller/bonus/shop',
        id: 'bonus_shop',
        children: [],
      },
      {
        icon: 'GiftOutlined',
        name: 'product.bonus',
        url: 'seller/bonus/product',
        id: 'bonus_product',
      },
    ],
  },
  {
    name: 'analytics.and.reports',
    id: 'analytics',
    icon: 'products',
    submenu: [
      {
        name: 'order',
        icon: 'orders',
        url: 'seller/report/orders',
        id: 'report-orders',
        children: [],
      },
    ],
  },
  {
    name: 'transaction',
    id: 'transaction_management',
    icon: 'wallet',
    submenu: [
      {
        name: 'payments',
        icon: 'wallet',
        url: 'seller/payments',
        id: 'payments',
        children: [],
      },
      {
        name: 'transactions',
        icon: 'transaction',
        url: 'seller/transactions',
        id: 'transactions',
        children: [],
      },
      {
        name: 'payment.from.admin',
        icon: 'moneyOut',
        url: 'seller/withdraws',
        id: 'withdraws',
        children: [],
      },
      {
        name: 'payouts',
        icon: 'dollar',
        url: 'seller/payouts',
        id: 'payouts',
        children: [],
      },
    ],
  },
  {
    name: 'business',
    id: 'business_management',
    icon: 'trophy',
    submenu: [
      // {
      //   name: 'subscriptions',
      //   icon: 'trophy',
      //   url: 'seller/subscriptions',
      //   id: 'subscription',
      //   children: [],
      // },
      {
        name: 'ad.packages',
        id: 'ad_packages',
        url: 'seller/advert',
        icon: 'MdOutlineTableBar',
      },
      {
        name: 'ads',
        id: 'shop_ads',
        url: 'seller/shop-ads',
        icon: 'appStore',
      },
    ],
  },
  {
    name: 'content',
    id: 'content_management',
    icon: 'appStoreAdd',
    submenu: [
      {
        name: 'stories',
        icon: 'BsClockHistory',
        url: 'seller/stories',
        id: 'seller_stories',
        children: [],
      },
      // {
      //   name: 'brands',
      //   icon: 'appStoreAdd',
      //   url: 'seller/brands',
      //   id: 'brands',
      //   children: [],
      // },
    ],
  },
  {
    name: 'logout',
    icon: 'logout',
    url: '',
    id: 'logout_01',
  },
];